### ISSUE TITLE
Group block nesting not working?

### ISSUE THREAD

**Issue by freds-dev** [KevinBatdorf/wavy-divider#5]
Hey, awesome tool!!

In my case the `wavy-divider-remove-margin` and `wavy-divider-remove-paddin` CSS tags are not working in a group.. Padding still stays the same but I'd like to have a smaller gap between the divider and the next element...

**Comment by KevinBatdorf** [comment]
Hey, thanks. it was fun to make :) 

It could be that WP changed how the block spacing works already. Could you share a link? If not can you share your theme name?
